export const ROLES = Object.freeze({
  ADMIN: 'Admin',
  CUSTOMER: 'Customer',
  FISHERMAN: 'Fisherman',
  BAIT_SELLER: 'BaitSeller',
  AUCTIONEER: 'Auctioneer',
});

export const SELLER_ROLES = [ROLES.FISHERMAN, ROLES.BAIT_SELLER];
export const ECOMMERCE_ROLES = [ROLES.CUSTOMER, ROLES.FISHERMAN, ROLES.BAIT_SELLER, ROLES.AUCTIONEER];

export const routeGuards = {
  'admin': (user) => !!user && user.role === ROLES.ADMIN,
  'cart': (user) => !!user && ECOMMERCE_ROLES.includes(user.role),
  'checkout': (user) => !!user && ECOMMERCE_ROLES.includes(user.role),
  'dashboard': (user) => !!user,
  'shipping': (user) => !!user && ECOMMERCE_ROLES.includes(user.role),
  'order-detail': (user) => !!user && ECOMMERCE_ROLES.includes(user.role),
  'profile': (user) => !!user,
  'auction-requests': (user) => !!user && user.role === ROLES.FISHERMAN,
  'auction-requests-review': (user) => !!user && (user.role === ROLES.AUCTIONEER || user.role === ROLES.ADMIN),
  'auctioneer-analytics': (user) => !!user && (user.role === ROLES.AUCTIONEER || user.role === ROLES.ADMIN),
  'subscriptions': (user) => !!user && (user.role === ROLES.CUSTOMER || user.role === ROLES.FISHERMAN || user.role === ROLES.BAIT_SELLER || user.role === ROLES.AUCTIONEER),
  'wallet': (user) => !!user,
};

export const routes = {
  "": () => import('../../pages/home.js'),
  login: () => import('../../pages/login.js'),
  register: () => import('../../pages/register.js'),
  "forgot-password": () => import('../../pages/forgot-password.js'),
  "reset-password": () => import('../../pages/reset-password.js'),
  products: () => import('../../pages/products.js'),
  "product-detail": () => import('../../pages/product-detail.js'),
  auctions: () => import('../../pages/auctions.js'),
  "auction-detail": () => import('../../pages/auction-detail.js'),
  cart: () => import('../../pages/cart.js'),
  checkout: () => import('../../pages/checkout.js'),
  dashboard: () => import('../../pages/dashboard.js'),
  "verify-email": () => import('../../pages/verify-email.js'),
  shipping: () => import('../../pages/shipping.js'),
  "seller-profile": () => import('../../pages/seller-profile.js'),
  "order-detail": () => import('../../pages/order-detail.js'),
  admin: () => import('../../pages/admin.js'),
  terms: () => import('../../pages/terms.js'),
  privacy: () => import('../../pages/privacy.js'),
  profile: () => import('../../pages/profile.js'),
  "auction-requests": () => import('../../pages/auction-requests.js'),
  "auction-requests-review": () => import('../../pages/auction-requests-review.js'),
  "auctioneer-analytics": () => import('../../pages/auctioneer-analytics.js'),
  subscriptions: () => import('../../pages/subscriptions.js'),
  wallet: () => import('../../pages/wallet.js'),
};

export const routeTitleKeys = {
  "": "home.welcome",
  login: "nav.login",
  register: "nav.register",
  "forgot-password": "auth.forgotPassword",
  "reset-password": "auth.resetPassword",
  products: "products.title",
  "product-detail": "products.title",
  auctions: "auctions.title",
  "auction-detail": "auctions.title",
  cart: "nav.cart",
  checkout: "cart.title",
  dashboard: "nav.dashboard",
  "verify-email": "verify.title",
  shipping: "shipping.title",
  "seller-profile": "seller.title",
  "order-detail": "order.title",
  admin: "admin.title",
  terms: "auth.termsAndConditions",
  privacy: "auth.privacyPolicy",
  profile: "dash.profile",
  "auction-requests": "auctionRequests.title",
  "auction-requests-review": "auctionRequestsReview.title",
  "auctioneer-analytics": "analytics.title",
  subscriptions: "subscriptions.title",
  wallet: "wallet.title",
};
